name = "WorldGenStudioPlugin"
version = "0.4.5-beta.26"
api-version = "0.4"
description = "Interactive In-Game WorldGen, Interceptor, and Scheduler Stress Test Suite"
main = "endstone_worldgen_studio:WorldGenStudioPlugin"

[commands.wg]
description = "WorldGen Studio & Chunk Interceptor Test Suite"
usages = ["/wg <gen|structure|benchmark|inspect> [args...]"]
permissions = ["wg.admin"]

[permissions."wg.admin"]
description = "Allows access to WorldGen Studio commands"
default = "op"
